"use strict";

/*
|--------------------------------------------------------------------------
| InstrumentSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use("Factory");
const Instrument = use("App/Models/Instrument");

class InstrumentSeeder {
  async run() {
    await Instrument.createMany([
      {
        id_instrument: "01",
        parent_id: null,
        seq_id: null,
        has_sub: 0,
        has_volume: 0,
        nama: "ITEM PEMERIKSAAN",
        volume_from: null,
        volume_to: null,
        volume_per: null,
        satuan: null,
        tera_baru_pengujian: null,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: null,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "0101",
        parent_id: "01",
        seq_id: null,
        has_sub: 1,
        has_volume: 0,
        nama: "ALAT PEMADAM KEBAKARAN",
        volume_from: null,
        volume_to: null,
        volume_per: null,
        satuan: null,
        tera_baru_pengujian: null,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: null,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "010101",
        parent_id: "0101",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "HYDRANT KEBAKARAN",
        volume_from: 1,
        volume_to: 1000,
        volume_per: 1,
        satuan: "TITIK",
        tera_baru_pengujian: 30000,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 30000,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "010102",
        parent_id: "0101",
        seq_id: null,
        has_sub: 1,
        has_volume: 0,
        nama: "SPRINGKLER",
        volume_from: null,
        volume_to: null,
        volume_per: null,
        satuan: null,
        tera_baru_pengujian: null,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: null,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "01010201",
        parent_id: "010102",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "SAMPAI DENGAN 2000 M2 ",
        volume_from: 1,
        volume_to: 2000,
        volume_per: 1,
        satuan: "M2",
        tera_baru_pengujian: 150,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 150,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "01010202",
        parent_id: "010102",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "LEBIH DARI 2000 M2 ",
        volume_from: 2001,
        volume_to: 300000,
        volume_per: 1,
        satuan: "M2",
        tera_baru_pengujian: 125,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 125,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "01010203",
        parent_id: "010102",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "MANUAL",
        volume_from: 1,
        volume_to: 300000,
        volume_per: 1,
        satuan: "M2",
        tera_baru_pengujian: 15000,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 15000,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "010103",
        parent_id: "0101",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "BLOWER",
        volume_from: 1,
        volume_to: 300000,
        volume_per: 1,
        satuan: "BUAH",
        tera_baru_pengujian: 75000,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 75000,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "010104",
        parent_id: "0101",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "APAR (ALAT PEMADAM KEBAKARAN RINGAN)",
        volume_from: 1,
        volume_to: 300000,
        volume_per: 1,
        satuan: "TABUNG",
        tera_baru_pengujian: 10000,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 10000,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "010105",
        parent_id: "0101",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "APAB (ALAT PEMADAM KEBAKARAN BERAT)",
        volume_from: 1,
        volume_to: 300000,
        volume_per: 1,
        satuan: "TABUNG",
        tera_baru_pengujian: 15000,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 15000,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "010106",
        parent_id: "0101",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "FIRE DAMPER (ALAT PENAHAN API)",
        volume_from: 1,
        volume_to: 300000,
        volume_per: 1,
        satuan: "BUAH",
        tera_baru_pengujian: 12000,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 12000,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "0102",
        parent_id: "01",
        seq_id: null,
        has_sub: 1,
        has_volume: 0,
        nama: "LAINNYA",
        volume_from: null,
        volume_to: null,
        volume_per: null,
        satuan: null,
        tera_baru_pengujian: null,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: null,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
      {
        id_instrument: "010201",
        parent_id: "0102",
        seq_id: null,
        has_sub: 0,
        has_volume: 1,
        nama: "INSTALASI KHUSUS",
        volume_from: 1,
        volume_to: 300000,
        volume_per: 1,
        satuan: "M2",
        tera_baru_pengujian: 5000,
        tera_baru_penjustiran: null,
        tera_ulang_pengujian: 5000,
        tera_ulang_penjustiran: null,
        tarif_per_jam: null,
      },
    ]);
  }
}

module.exports = InstrumentSeeder;
